workflowVersion: 1.0.0
sources:
    my-first-source:
        inputs:
            - location: https://rcd.nscampfire.com/openapi.json
targets:
    my-first-target:
        target: python
        source: my-first-source
